name: base_models
description: Flutter package for have base models.
version: 0.0.1
repository: https://github.com/JoseTabares/base_models

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
